{% set goname = "github.com/terraform-linters/tflint" %}
{% set version = "0.15.3" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: 878498373f45e6a34a3e1016339309ba973d7f13887430ec9674d745a751e170

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go install -v .

requirements:
  build:
    - {{ compiler('go') }}

test:
  requires:
    - m2-bash  # [win]
  commands:
    - bash -c "{{ name|lower }} -v"

about:
  home: https://github.com/terraform-linters/tflint
  license: MPL 2.0
  license_file: {{ pkg_src }}/LICENSE
  summary: TFLint is a Terraform linter focused on possible errors, best practices, etc.
  dev_url: https://github.com/terraform-linters/tflint.git

extra:
  recipe-maintainers:
    - sodre
    - mariusvniekerk
