{% set goname = "github.com/terraform-linters/tflint" %}
{% set version = "0.47.0" %}

{% set name = goname.split('/')[-1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: 2e9cefebb18e4fb15faa217dd2005feda2fdcabb7948d1298773b8458bb04abe

build:
  number: 1
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses
    - go build -v -o $PREFIX/bin/{{ name|lower }}  # [not win]
    - go build -v -o %LIBRARY_PREFIX%/{{ name|lower }}.exe  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - m2-bash  # [win]
  commands:
    - bash -c "{{ name|lower }} -v"

about:
  home: https://github.com/terraform-linters/tflint
  license: MPL 2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  summary: TFLint is a Terraform linter focused on possible errors, best practices, etc.
  dev_url: https://github.com/terraform-linters/tflint.git

extra:
  recipe-maintainers:
    - sodre
    - mariusvniekerk
    - pavelzw
