{% set goname = "github.com/terraform-linters/tflint" %}
{% set version = "0.50.3" %}

{% set name = goname.split('/')[-1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: e90acdbf4cd1dc936e50b580ade53583baced53a93b3b01cee3e073b233ef8c5

build:
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses
    - go build -v -o $PREFIX/bin/tflint  # [not win]
    - go build -v -o %LIBRARY_BIN%\tflint.exe  # [win]
    # Clear out cache to avoid file not removable warnings
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)  # [unix]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - tflint -v
    - tflint --help

about:
  home: https://github.com/terraform-linters/tflint
  license: MPL 2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  summary: TFLint is a Terraform linter focused on possible errors, best practices, etc.
  dev_url: https://github.com/terraform-linters/tflint.git

extra:
  recipe-maintainers:
    - sodre
    - mariusvniekerk
    - pavelzw
