{% set goname = "github.com/terraform-linters/tflint" %}
{% set version = "0.40.1" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: cc7612386cb63a72a6b49e70e71996c5d6504f66538ad9e9c9a8d374723aa0a4

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go install -v .

requirements:
  build:
    - {{ compiler('go') }}

test:
  requires:
    - m2-bash  # [win]
  commands:
    - bash -c "{{ name|lower }} -v"

about:
  home: https://github.com/terraform-linters/tflint
  license: MPL 2.0
  license_file: {{ pkg_src }}/LICENSE
  summary: TFLint is a Terraform linter focused on possible errors, best practices, etc.
  dev_url: https://github.com/terraform-linters/tflint.git

extra:
  recipe-maintainers:
    - sodre
    - mariusvniekerk
