context:
  version: 0.61.0

package:
  name: tflint
  version: ${{ version }}

source:
  - target_directory: src
    url: https://github.com/terraform-linters/tflint/archive/v${{ version }}.tar.gz
    sha256: d99c9eb3003375a4220607e1b479c9292450fd2c576549b1887f1c7259730e17


build:
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses
    - if: unix
      then: go build -v -o $PREFIX/bin/tflint -ldflags="-s -w"
      else: go build -v -o %LIBRARY_BIN%\tflint.exe -ldflags="-s"

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script:
      - tflint --help
      - tflint -v
  - package_contents:
      bin:
        - tflint
      strict: true

about:
  homepage: https://github.com/terraform-linters/tflint
  license: MPL-2.0 AND BUSL-1.1
  license_file:
    - src/LICENSE
    - src/LICENSE-BUSL
    - library_licenses/
  summary: TFLint is a Terraform linter focused on possible errors, best practices, etc.
  repository: https://github.com/terraform-linters/tflint.git

extra:
  recipe-maintainers:
    - sodre
    - mariusvniekerk
    - pavelzw
