travis:
  secure:
    BINSTAR_TOKEN: ojmQKe5klnY+BXFfUDJ/vMx4sOF4VuNi4hK+qoWYa+xMpNV4F4oDnr3NXuJT98UjbxqUaZFKJDv7vow2ENYmPcuzgfO8Quvx+3jx8Z2ik/GuT0BoMQ/QMCcbcVXl8K7IHghyHpHWB60vkLR7YQBaj9P7wbQTIV8Uz2H8BFWVb/eaNE3CyfiiWZeHG8Q1ZimFqlXMPvMXjf3HBNIoNT+nUkYydekakYQyo9kTB4Um9sYdNq31UU4GPJET8doKOQlO4ueF5Sw6bXYy8CuSF/cMLshxywV3fpsuKozU8ShKReUu8es5m7VQn2kCobC0TymjZlD0OfnkqOdA9Y7+WGqk/3f9Podyms71bAVNHPK1XxzHpCTv/g2lAjNJApBcdtchQLh4cdFbNW+oq5CnNDSemOJLqfrwr7vuQ5DFVm7G3Li+7WBaIvk1JeiEDIkTHIm62XLUIuQST+8IrBxVH7aPdr4RKPbTR5mCoJr/Dt8gMoS7w0WDPnnofYs3rc+2GfEhF//H0PHMY2EJxJFdED7IfEiRmvl6ZhNWFfNaQsbqg3vdlnBrOiIBeMYEJlPxB0ipiVaXTkkiv1LKNDABimp+DyYyqFqghpUhU8cN7c9JbjRdlb5kis15eI8Ql1B+2V6IIQB+yHH8MUajV+7RJbb0yYQ3jH0GtxplsqptZpTJCLE=
bot:
  automerge: true
conda_forge_output_validation: true
